[build]
  command = "pnpm build"  # 使用 pnpm 构建命令
  publish = "dist"        # 发布到 dist 目录

# 启用 Brotli 压缩（加速传输）
[build.processing]
brotli = true

# 单页应用路由重定向
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200  # 正确使用 200 而非 30x

# 静态资源缓存策略
[[headers]]
  for = "/js/*"  # 匹配 JS 文件
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # 1年缓存+不可变标记

[[headers]]
  for = "/css/*"  # 匹配 CSS 文件
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*"  # 匹配图片文件
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML 是入口文件，需要即时更新，否则用户可能看到旧版本
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"  # 禁用缓存

# 其他静态资源（字体等）的缓存规则
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 兜底资源设置（1小时缓存）
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"